### ISSUE TITLE
retrain last-layer / fine-tune

### ISSUE THREAD

**Issue by culurciello** [karandwivedi42/imagenet-multiGPU.torchnet#1]
Well done here. A nice feature to add is to be able to fine-tune a network and / or train last layer, see here example:
https://github.com/e-lab/imagenet-multiGPU.torch/blob/e_data/opts.lua

**Comment by karandwivedi42** [comment]
You can see the models/alexnet_init.lua file. For now that is how I do fine-tuning.

I load the model, remove the last layer manually. Add its replacement. And between these, there is nn.ScaleGrad layer that serves to lower the lr for the pretrained part.
