### ISSUE TITLE
Fails with luajit

### ISSUE THREAD

**Issue by karandwivedi42** [karandwivedi42/imagenet-multiGPU.torchnet#10]
Storing file names in table of strings leads to error in luajit because of 2gb limit.

Solution - Implement something like:
https://github.com/soumith/imagenet-multiGPU.torch/blob/master/dataset.lua#L306

**Comment by fmassa** [comment]
You could also look into using `tds.Vec` or `tds.Hash`.

**Comment by karandwivedi42** [comment]
@fmassa tds was perfect. Thanks :)

**Comment by culurciello** [comment]
thanks a lot for your kind help @fmassa , well done @karandwivedi42
