### ISSUE TITLE
multi gpu not working, and out of mem with larger threads. Also slow.

### ISSUE THREAD

**Issue by culurciello** [karandwivedi42/imagenet-multiGPU.torchnet#5]
E. Culurciello
August 7th 2016

Speed test on image net AlexNet OWT

with:
https://github.com/karandwivedi42/imagenet-multiGPU.torchnet

elab@GPU8 ~/euge/imagenet-multiGPU.torchnet [master*]$ th train.lua -d /media/SuperSSD/ILSVRC2012 -c ImageNet.t7 -m models/alexnet.lua

Note: this has only 4 threads,

Epoch: [1][1/10009]     Time 41.107 Err 6.9027 LR 1e-02 DataLoadingTime 35.518
Epoch: [1][2/10009]     Time 0.544 Err 6.9279 LR 1e-02 DataLoadingTime 0.021
Epoch: [1][3/10009]     Time 0.132 Err 6.9441 LR 1e-02 DataLoadingTime 0.096
Epoch: [1][4/10009]     Time 0.133 Err 6.9792 LR 1e-02 DataLoadingTime 0.097
Epoch: [1][5/10009]     Time 0.133 Err 6.9654 LR 1e-02 DataLoadingTime 0.097
Epoch: [1][6/10009]     Time 0.132 Err 6.9648 LR 1e-02 DataLoadingTime 0.095
Epoch: [1][7/10009]     Time 0.132 Err 6.9509 LR 1e-02 DataLoadingTime 0.096
Epoch: [1][8/10009]     Time 0.132 Err 6.9476 LR 1e-02 DataLoadingTime 0.096
Epoch: [1][9/10009]     Time 1.576 Err 6.9273 LR 1e-02 DataLoadingTime 1.540
Epoch: [1][10/10009]    Time 3.898 Err 6.9115 LR 1e-02 DataLoadingTime 3.859
Epoch: [1][11/10009]    Time 0.643 Err 6.9211 LR 1e-02 DataLoadingTime 0.604
Epoch: [1][12/10009]    Time 1.109 Err 6.9469 LR 1e-02 DataLoadingTime 1.073
Epoch: [1][13/10009]    Time 0.590 Err 6.9213 LR 1e-02 DataLoadingTime 0.552
Epoch: [1][14/10009]    Time 0.735 Err 6.9483 LR 1e-02 DataLoadingTime 0.700
Epoch: [1][15/10009]    Time 0.140 Err 6.9334 LR 1e-02 DataLoadingTime 0.104
Epoch: [1][16/10009]    Time 3.235 Err 6.9136 LR 1e-02 DataLoadingTime 3.199
Epoch: [1][17/10009]    Time 0.132 Err 6.9158 LR 1e-02 DataLoadingTime 0.096
Epoch: [1][18/10009]    Time 0.132 Err 6.9711 LR 1e-02 DataLoadingTime 0.096
Epoch: [1][19/10009]    Time 0.243 Err 6.9091 LR 1e-02 DataLoadingTime 0.208
Epoch: [1][20/10009]    Time 2.253 Err 6.9536 LR 1e-02 DataLoadingTime 2.217
Epoch: [1][21/10009]    Time 1.263 Err 6.9631 LR 1e-02 DataLoadingTime 1.227
Epoch: [1][22/10009]    Time 0.432 Err 6.9448 LR 1e-02 DataLoadingTime 0.396
Epoch: [1][23/10009]    Time 0.564 Err 6.9113 LR 1e-02 DataLoadingTime 0.527
Epoch: [1][24/10009]    Time 0.518 Err 6.9246 LR 1e-02 DataLoadingTime 0.482
Epoch: [1][25/10009]    Time 2.376 Err 6.9819 LR 1e-02 DataLoadingTime 2.338
Epoch: [1][26/10009]    Time 0.486 Err 6.9789 LR 1e-02 DataLoadingTime 0.449
Epoch: [1][27/10009]    Time 2.046 Err 6.9642 LR 1e-02 DataLoadingTime 2.011
Epoch: [1][28/10009]    Time 0.132 Err 6.9728 LR 1e-02 DataLoadingTime 0.092
Epoch: [1][29/10009]    Time 0.787 Err 6.8990 LR 1e-02 DataLoadingTime 0.751
Epoch: [1][30/10009]    Time 0.133 Err 6.9336 LR 1e-02 DataLoadingTime 0.094
Epoch: [1][31/10009]    Time 3.687 Err 6.9045 LR 1e-02 DataLoadingTime 3.648
Epoch: [1][32/10009]    Time 1.315 Err 6.9149 LR 1e-02 DataLoadingTime 1.279
Epoch: [1][33/10009]    Time 0.484 Err 6.9371 LR 1e-02 DataLoadingTime 0.447
Epoch: [1][34/10009]    Time 0.906 Err 6.9351 LR 1e-02 DataLoadingTime 0.869
Epoch: [1][35/10009]    Time 1.000 Err 6.8956 LR 1e-02 DataLoadingTime 0.962
Epoch: [1][36/10009]    Time 0.378 Err 6.9621 LR 1e-02 DataLoadingTime 0.340
Epoch: [1][37/10009]    Time 0.720 Err 6.9073 LR 1e-02 DataLoadingTime 0.684
Epoch: [1][38/10009]    Time 2.889 Err 6.9671 LR 1e-02 DataLoadingTime 2.850
Epoch: [1][39/10009]    Time 1.368 Err 6.9442 LR 1e-02 DataLoadingTime 1.331
Epoch: [1][40/10009]    Time 1.777 Err 6.9094 LR 1e-02 DataLoadingTime 1.740
Epoch: [1][41/10009]    Time 0.274 Err 6.9576 LR 1e-02 DataLoadingTime 0.238
Epoch: [1][42/10009]    Time 0.911 Err 6.8765 LR 1e-02 DataLoadingTime 0.870
Epoch: [1][43/10009]    Time 0.171 Err 6.9280 LR 1e-02 DataLoadingTime 0.134
Epoch: [1][44/10009]    Time 1.971 Err 6.9575 LR 1e-02 DataLoadingTime 1.935
Epoch: [1][45/10009]    Time 1.526 Err 6.9391 LR 1e-02 DataLoadingTime 1.489
Epoch: [1][46/10009]    Time 1.123 Err 6.9666 LR 1e-02 DataLoadingTime 1.086

PROBLEM: multi-GPU not working:

elab@GPU8 ~/euge/imagenet-multiGPU.torchnet [master*]$ th train.lua -d /media/SuperSSD/ILSVRC2012 -c ImageNet.t7 -m models/alexnet.lua -nGPU 4

/home/elab/torch/install/bin/luajit: /home/elab/torch/install/share/lua/5.1/threads/threads.lua:183: [thread 2 callback] /home/elab/euge/imagenet-multiGPU.torchnet/models/utils.lua:41: module '../scalegrad' not found:
        no field package.preload['../scalegrad']
        no file '/home/elab/.luarocks/share/lua/5.1////scalegrad.lua'
        no file '/home/elab/.luarocks/share/lua/5.1////scalegrad/init.lua'
        no file '/home/elab/torch/install/share/lua/5.1////scalegrad.lua'
        no file '/home/elab/torch/install/share/lua/5.1////scalegrad/init.lua'
        no file './///scalegrad.lua'
        no file '/home/elab/torch/install/share/luajit-2.1.0-beta1////scalegrad.lua'
        no file '/usr/local/share/lua/5.1////scalegrad.lua'
        no file '/usr/local/share/lua/5.1////scalegrad/init.lua'
        no file '/home/elab/torch/install/lib////scalegrad.so'
        no file '/home/elab/.luarocks/lib/lua/5.1////scalegrad.so'
        no file '/home/elab/torch/install/lib/lua/5.1////scalegrad.so'
        no file '/home/elab/torch/install/lib////scalegrad.so'
        no file './///scalegrad.so'
        no file '/usr/local/lib/lua/5.1////scalegrad.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/elab/torch/install/lib/.so'
        no file '/home/elab/.luarocks/lib/lua/5.1/.so'
        no file '/home/elab/torch/install/lib/lua/5.1/.so'
        no file '/home/elab/torch/install/lib/.so'
        no file './.so'
        no file '/usr/local/lib/lua/5.1/.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/elab/euge/imagenet-multiGPU.torchnet/models/utils.lua:41: in function </home/elab/euge/imagenet-multiGPU.torchnet/models/utils.lua:39>
        [C]: in function 'xpcall'
        /home/elab/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
        /home/elab/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/elab/torch/install/share/lua/5.1/threads/queue.lua:41>
        [C]: in function 'pcall'
        /home/elab/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
        [string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
        [C]: in function 'error'
        /home/elab/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
        /home/elab/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
        /home/elab/torch/install/share/lua/5.1/threads/threads.lua:142: in function 'specific'
        /home/elab/torch/install/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
        ...b/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:704: in function 'setup'
        ...b/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:714: in function 'exec'
        ...b/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:104: in function 'flattenParameters'
        ...b/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:128: in function 'getParameters'
        ...ch/install/share/lua/5.1/torchnet/engine/optimengine.lua:86: in function 'train'
        train.lua:237: in main chunk
        [C]: in function 'dofile'
        ...elab/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x004065d0

image manipulation is slow here

suggest looking into copying this routine:
https://github.com/e-lab/imagenet-multiGPU.torch/blob/master/donkey.lua#L55

image.scale —> use “simple” interpolation for speed, but is not used in fast routine above

PROBLEM: when we try 12 or even 8 threads:

elab@GPU8 ~/euge/imagenet-multiGPU.torchnet [master*]$ th train.lua -d /media/SuperSSD/ILSVRC2012 -c ImageNet.t7 -m models/alexnet.lua --nThread 12

 it fails: FATAL THREAD PANIC: (pcall) not enough memory

with:
https://github.com/e-lab/imagenet-multiGPU.torch

elab@GPU8 ~/euge/imagenet-multiGPU.torch [master*]$ th main.lua -data /media/SuperSSD/ILSVRC2012 -backend cudnn -netType alexnetowt -nGPU 4 -nDonkeys 12

Epoch: [1][1/10000]     Time 5.216 Err 6.9055 Top1-%: 0.00 LR 1e-02 DataLoadingTime 6.888
Epoch: [1][2/10000]     Time 0.133 Err 6.9082 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.013
Epoch: [1][3/10000]     Time 0.155 Err 6.9078 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.014
Epoch: [1][4/10000]     Time 0.136 Err 6.9078 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.007
Epoch: [1][5/10000]     Time 0.129 Err 6.9092 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.008
Epoch: [1][6/10000]     Time 0.125 Err 6.9083 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.004
Epoch: [1][7/10000]     Time 0.127 Err 6.9077 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.005
Epoch: [1][8/10000]     Time 0.127 Err 6.9052 Top1-%: 0.78 LR 1e-02 DataLoadingTime 0.014
Epoch: [1][9/10000]     Time 0.127 Err 6.9086 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.008
Epoch: [1][10/10000]    Time 0.140 Err 6.9075 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.012
Epoch: [1][11/10000]    Time 0.126 Err 6.9081 Top1-%: 0.78 LR 1e-02 DataLoadingTime 0.012
Epoch: [1][12/10000]    Time 0.127 Err 6.9056 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.013
Epoch: [1][13/10000]    Time 0.125 Err 6.9092 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.011
Epoch: [1][14/10000]    Time 0.128 Err 6.9097 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.009
Epoch: [1][15/10000]    Time 0.125 Err 6.9061 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.016
Epoch: [1][16/10000]    Time 0.127 Err 6.9069 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.011
Epoch: [1][17/10000]    Time 0.127 Err 6.9065 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.009
Epoch: [1][18/10000]    Time 0.127 Err 6.9077 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.014
Epoch: [1][19/10000]    Time 0.127 Err 6.9080 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.011
Epoch: [1][20/10000]    Time 0.132 Err 6.9074 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.013
Epoch: [1][21/10000]    Time 0.128 Err 6.9084 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.009
Epoch: [1][22/10000]    Time 0.144 Err 6.9068 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.009
Epoch: [1][23/10000]    Time 0.131 Err 6.9078 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.014
Epoch: [1][24/10000]    Time 0.127 Err 6.9074 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.008
Epoch: [1][25/10000]    Time 0.127 Err 6.9063 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.005
Epoch: [1][26/10000]    Time 0.126 Err 6.9093 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.006
Epoch: [1][27/10000]    Time 0.127 Err 6.9090 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.009
Epoch: [1][28/10000]    Time 0.127 Err 6.9066 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.004
Epoch: [1][29/10000]    Time 0.131 Err 6.9083 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.005
Epoch: [1][30/10000]    Time 0.127 Err 6.9083 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.005
Epoch: [1][31/10000]    Time 0.128 Err 6.9071 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.006
Epoch: [1][32/10000]    Time 0.141 Err 6.9081 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.005
Epoch: [1][33/10000]    Time 0.127 Err 6.9083 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.005
Epoch: [1][34/10000]    Time 0.127 Err 6.9060 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.005
Epoch: [1][35/10000]    Time 0.129 Err 6.9074 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.005
Epoch: [1][36/10000]    Time 0.127 Err 6.9081 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.012
Epoch: [1][37/10000]    Time 0.132 Err 6.9093 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.196
Epoch: [1][38/10000]    Time 0.129 Err 6.9097 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.035
Epoch: [1][39/10000]    Time 0.127 Err 6.9055 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.106
Epoch: [1][40/10000]    Time 0.127 Err 6.9080 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.045
Epoch: [1][41/10000]    Time 0.127 Err 6.9099 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.006
Epoch: [1][42/10000]    Time 0.140 Err 6.9064 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.014
Epoch: [1][43/10000]    Time 0.126 Err 6.9094 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.011
Epoch: [1][44/10000]    Time 0.137 Err 6.9083 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.006
Epoch: [1][45/10000]    Time 0.128 Err 6.9100 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.200
Epoch: [1][46/10000]    Time 0.127 Err 6.9063 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.254
Epoch: [1][47/10000]    Time 0.127 Err 6.9099 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.042
Epoch: [1][48/10000]    Time 0.139 Err 6.9086 Top1-%: 0.00 LR 1e-02 DataLoadingTime 0.030

**Comment by karandwivedi42** [comment]
Regarding scalegrad, it is included in the repo. Try changing the path.
Regarding memory, I don't really know. You can try https://github.com/torchnet/torchnet/pull/43, it really helped me.
Thanks for the image manipulation suggestion.

**Comment by culurciello** [comment]
Weird with 4 threads I can run at 20% of system memory (not GPU mem), but with 6 or more threads it dies, even though I do nto see it going above 5% on htop...

**Comment by karandwivedi42** [comment]
Did you try https://github.com/torchnet/torchnet/pull/43 ?

**Comment by culurciello** [comment]
Uhm, I believe this is something torchnet should have. I am not sure what is the best position for it, but maybe it should not have all of these calls. I think one time per thread should be enough, and not slow down everything too much. I want to confirm with torchnet coders

**Comment by karandwivedi42** [comment]
Did it help you though?

**Comment by lvdmaaten** [comment]
I'm routinely running this kind of code with 10+ threads. Depending on the speed of disk access, you should be able to completely hide the data-loading cost.

It's not clear to me that torchnet is the best place to add gc-calls: the exact behavior may vary between Lua(JIT) versions and between data loaders (you don't want to gc, say, after each sentence you read in from a text file). The various closures in torchnet give you plenty of opportunity to include gc-calls where needed.

**Comment by culurciello** [comment]
Thank you so much @lvdmaaten this is the info we were looking for. 
Easier to add these to our code. But then why so many gc calls here:
https://github.com/torchnet/torchnet/search?utf8=%E2%9C%93&q=collectgarbage
And we may not have access to thread in our code... will try!

**Comment by karandwivedi42** [comment]
@culurciello I hope the issue is not there in the new code.

**Comment by culurciello** [comment]
well done on new version
I was able to use more threads, with a small version of a dataset:
th main.lua -data /media/SuperSSD/ILSVRC2012-test -netType alexnetowtbn -nGPU 4 -nDonkeys 12  -batchSize 128

with the full imagenet, it still fails with  out of memory, maybe the image table is too large?
That may be an issue with torfchnet

**Comment by karandwivedi42** [comment]
Solved in https://github.com/karandwivedi42/imagenet-multiGPU.torchnet/pull/11

**Comment by culurciello** [comment]
well done, this is great
